version: '{build}'
image: Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
  - firebird_selection: FB30
  - firebird_selection: FB25
test: off
init:
  - git config --global core.autocrlf true
before_build:
  - ps: $baseDir = Resolve-Path .
build_script:
  - ps: $env:build_wix = 'C:\Program Files (x86)\WiX Toolset v3.11\bin'
  - ps: "& $baseDir\\Provider\\build.ps1 -Configuration $env:CONFIGURATION"
after_build:
  - ps: gci "$baseDir\Provider\out" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test_script:
  - ps: $env:tests_firebird_dir = 'C:\firebird'
  - ps: "& $baseDir\\Provider\\tests.ps1 -Configuration $env:CONFIGURATION -FirebirdSelection $env:firebird_selection -TestSuite Tests-All"
