name: CI

on: [push, pull_request]

env:
  CONFIGURATION: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  ci:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        FIREBIRD_SELECTION: [FB30, FB40]
        TEST_SUITE: [Tests-FirebirdClient-Default-Compression-CryptRequired, Tests-FirebirdClient-Default-NoCompression-CryptRequired, Tests-FirebirdClient-Default-Compression-CryptDisabled, Tests-FirebirdClient-Default-NoCompression-CryptDisabled, Tests-FirebirdClient-Embedded, Tests-EFCore, Tests-EFCore-Functional, Tests-EF6]
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          try {
            $env:build_wix = 'C:\Program Files (x86)\WiX Toolset v3.11\bin'

            .\Provider\build.ps1 -Configuration ${{ env.CONFIGURATION }}
            exit $LASTEXITCODE
          }
          catch {
            echo $_
            exit 1
          }
        shell: powershell

      - name: Tests
        run: |
          try {
            $env:tests_firebird_dir = 'C:\firebird'

            .\Provider\tests.ps1 -Configuration ${{ env.CONFIGURATION }} -FirebirdSelection ${{ matrix.FIREBIRD_SELECTION }} -TestSuite ${{ matrix.TEST_SUITE }}
            exit $LASTEXITCODE
          }
          catch {
            echo $_
            exit 1
          }
        shell: powershell

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: '.\\Provider\\out\\'